export const endpoints= {
    auth: {
        me: '/api/auth/me',
        signIn: '/api/auth/login',
      },

    sliderVideos:{
      list:"/api/video/list",
      create:"/api/video/create",
      delete:"/api/video/delete/"
    },
    getFile:{
      getByFileName:"api/file/getFile/"
    },
    file:{
      upload:"/api/file/uploadFile",
    },
    media:{
      list:"/api/news/list",
      listAll:"/api/news/listAll",
      delete:"/api/news/delete/",
      getById:"/api/news/getWithTranslation/",
      create:"/api/news/create",
      update:"/api/news/",
    },
    career:{
      list:"/api/career/list",
      listAll:"/api/career/listAll",
      getWithTranslation:"/api/career/getWithTranslation/",
      create:"/api/career/create",
      delete: "/api/career/delete/",
      getById:"/api/career/getWithTranslation/",
      update:"/api/career/",
    },
    contact:{
      list:"/api/contact-info/list",
      create:"/api/contact-info/create",
      update:"/api/contact-info/"
    },
    about:{
      info:{
        create:"/api/about/create",
        update:"/api/about/",
        getAll:"/api/about/listAll",
      },
      value:{
        getAll:"/api/value/list",
        getById:"/api/value/getWithTranslation/",
        update:"/api/value/",
        create:"/api/value/create"
      },
      mission:{
        getAll:"/api/mission/list",
        getById:"/api/mission/getWithTranslation/",
        update:"/api/mission/",
        create:"/api/mission/create"
      },
      history:{
        getAll:"/api/history/listAll",
        create:"/api/history/create",
        update:"/api/history/",
      },
      chronology:{
        list:"/api/chronology/list",
        getAll:"/api/chronology/listAll",
        delete:"/api/chronology/delete/",
        create:"/api/chronology/create",
        update:"/api/chronology/",
        getById:"/api/chronology/getWithTranslation/",
      },
      founderMessage:{
        getAll:"/api/founderMessage/listAll",
        create:"/api/founderMessage/create",
        update:"/api/founderMessage/",
      }
    }
}